name: Gulp Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Gulp CLI globally (if needed)
        run: npm install --global gulp-cli

      - name: Run Gulp build
        run: gulp build

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
